"""Initial schema

Revision ID: 29923ac4423d
Revises: a75ff9a39669
Create Date: 2025-12-29 03:08:31.471973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29923ac4423d'
down_revision: Union[str, None] = 'a75ff9a39669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(length=100), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('spotify_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['scent_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_links_memory_id'), 'spotify_links', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_links_memory_id'), table_name='spotify_links')
    op.drop_table('spotify_links')
    # ### end Alembic commands ###
