"""add summary to scent_memories

Revision ID: 5ebd622f89c9
Revises: 98cd0dbbf233
Create Date: 2026-01-09 20:10:46.714571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebd622f89c9'
down_revision: Union[str, None] = '98cd0dbbf233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scent_memories', sa.Column('summary', sa.String(length=500), nullable=True))
    op.add_column('scent_profiles', sa.Column('top_notes', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('scent_profiles', sa.Column('heart_notes', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('scent_profiles', sa.Column('base_notes', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('scent_profiles', sa.Column('emotional_preferences', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('spotify_links', 'lyrics')
    op.drop_column('spotify_links', 'album_art')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_links', sa.Column('album_art', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('spotify_links', sa.Column('lyrics', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('scent_profiles', 'emotional_preferences')
    op.drop_column('scent_profiles', 'base_notes')
    op.drop_column('scent_profiles', 'heart_notes')
    op.drop_column('scent_profiles', 'top_notes')
    op.drop_column('scent_memories', 'summary')
    # ### end Alembic commands ###
