"""Add Spotify links and music analysis

Revision ID: 98cd0dbbf233
Revises: 525b80ab9040
Create Date: 2026-01-02 18:00:56.527477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cd0dbbf233'
down_revision: Union[str, None] = '525b80ab9040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_links', sa.Column('album_art', sa.String(length=500), nullable=True))
    op.add_column('spotify_links', sa.Column('lyrics', sa.Text(), nullable=True))
    op.add_column('spotify_links', sa.Column('lyrics_analysis', sa.JSON(), nullable=True))
    op.alter_column('spotify_links', 'track_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('spotify_links', 'artist_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('spotify_links', 'spotify_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('spotify_links', 'track_id')
    op.drop_column('spotify_links', 'preview_url')
    op.drop_column('spotify_links', 'album_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_links', sa.Column('album_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('spotify_links', sa.Column('preview_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('spotify_links', sa.Column('track_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('spotify_links', 'spotify_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('spotify_links', 'artist_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('spotify_links', 'track_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('spotify_links', 'lyrics_analysis')
    op.drop_column('spotify_links', 'lyrics')
    op.drop_column('spotify_links', 'album_art')
    # ### end Alembic commands ###
