"""Initial schema

Revision ID: a75ff9a39669
Revises: 
Create Date: 2025-12-28 03:20:47.925458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a75ff9a39669'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tuning_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('training_file_id', sa.String(), nullable=True),
    sa.Column('openai_job_id', sa.String(), nullable=True),
    sa.Column('fine_tuned_model_id', sa.String(), nullable=True),
    sa.Column('training_example_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openai_job_id')
    )
    op.create_index(op.f('ix_fine_tuning_jobs_status'), 'fine_tuning_jobs', ['status'], unique=False)
    op.create_table('fragrances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fragrance_family', sa.String(length=100), nullable=True),
    sa.Column('subfamilies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes_top', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes_middle', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes_base', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('intensity', sa.String(length=50), nullable=True),
    sa.Column('longevity', sa.String(length=50), nullable=True),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('perfumer', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragrances_brand'), 'fragrances', ['brand'], unique=False)
    op.create_index(op.f('ix_fragrances_name'), 'fragrances', ['name'], unique=False)
    op.create_index(op.f('ix_fragrances_vector_id'), 'fragrances', ['vector_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_name'), 'notes', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fragrance_notes',
    sa.Column('fragrance_id', sa.UUID(), nullable=True),
    sa.Column('note_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE')
    )
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Enum('RECOMMENDATION', 'MEMORY_SEARCH', 'COMPARISON', name='querytype'), nullable=True),
    sa.Column('retrieved_chunks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_created_at'), 'query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('scent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('memory_type', sa.Enum('TEXT', 'PHOTO', 'PDF', 'AUDIO', name='memory_type_enum'), nullable=False),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scent_memories_created_at'), 'scent_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_scent_memories_memory_type'), 'scent_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_scent_memories_processed'), 'scent_memories', ['processed'], unique=False)
    op.create_index(op.f('ix_scent_memories_user_id'), 'scent_memories', ['user_id'], unique=False)
    op.create_table('scent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_families', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('disliked_notes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('intensity_preference', sa.String(length=50), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('total_memories', sa.Integer(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('training_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('completion', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('included_in_training', sa.Boolean(), nullable=True),
    sa.Column('training_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['training_job_id'], ['fine_tuning_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_fragrances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fragrance_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('wishlist', sa.Boolean(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fragrance_id', name='unique_user_fragrance')
    )
    op.create_index(op.f('ix_user_fragrances_fragrance_id'), 'user_fragrances', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_user_fragrances_user_id'), 'user_fragrances', ['user_id'], unique=False)
    op.create_table('extracted_scents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('fragrance_id', sa.UUID(), nullable=True),
    sa.Column('scent_name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memory_id'], ['scent_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_scents_fragrance_id'), 'extracted_scents', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_extracted_scents_memory_id'), 'extracted_scents', ['memory_id'], unique=False)
    op.create_table('image_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('detected_objects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dominant_colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('setting', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['scent_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_memory_id'), 'image_analyses', ['memory_id'], unique=True)
    op.create_table('memory_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['scent_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_order', 'memory_chunks', ['memory_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_memory_chunks_memory_id'), 'memory_chunks', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_vector_id'), 'memory_chunks', ['vector_id'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('fragrance_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fragrance_id'], ['fragrances.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_fragrance_id'), 'recommendations', ['fragrance_id'], unique=False)
    op.create_index(op.f('ix_recommendations_query_id'), 'recommendations', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_query_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_fragrance_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_memory_chunks_vector_id'), table_name='memory_chunks')
    op.drop_index(op.f('ix_memory_chunks_memory_id'), table_name='memory_chunks')
    op.drop_index('idx_memory_order', table_name='memory_chunks')
    op.drop_table('memory_chunks')
    op.drop_index(op.f('ix_image_analyses_memory_id'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_extracted_scents_memory_id'), table_name='extracted_scents')
    op.drop_index(op.f('ix_extracted_scents_fragrance_id'), table_name='extracted_scents')
    op.drop_table('extracted_scents')
    op.drop_index(op.f('ix_user_fragrances_user_id'), table_name='user_fragrances')
    op.drop_index(op.f('ix_user_fragrances_fragrance_id'), table_name='user_fragrances')
    op.drop_table('user_fragrances')
    op.drop_table('training_examples')
    op.drop_table('scent_profiles')
    op.drop_index(op.f('ix_scent_memories_user_id'), table_name='scent_memories')
    op.drop_index(op.f('ix_scent_memories_processed'), table_name='scent_memories')
    op.drop_index(op.f('ix_scent_memories_memory_type'), table_name='scent_memories')
    op.drop_index(op.f('ix_scent_memories_created_at'), table_name='scent_memories')
    op.drop_table('scent_memories')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_created_at'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_table('fragrance_notes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notes_name'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_fragrances_vector_id'), table_name='fragrances')
    op.drop_index(op.f('ix_fragrances_name'), table_name='fragrances')
    op.drop_index(op.f('ix_fragrances_brand'), table_name='fragrances')
    op.drop_table('fragrances')
    op.drop_index(op.f('ix_fine_tuning_jobs_status'), table_name='fine_tuning_jobs')
    op.drop_table('fine_tuning_jobs')
    # ### end Alembic commands ###
