"""add scent_family to extracted_scents

Revision ID: e8c67008e5c0
Revises: 5ebd622f89c9
Create Date: 2026-01-16 21:26:12.235570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c67008e5c0'
down_revision: Union[str, None] = '5ebd622f89c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_scents', sa.Column('scent_family', sa.String(length=100), nullable=True))
    op.add_column('extracted_scents', sa.Column('top_notes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('extracted_scents', sa.Column('heart_notes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('extracted_scents', sa.Column('base_notes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('extracted_scents', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('extracted_scents', sa.Column('emotion', sa.String(length=100), nullable=True))
    op.drop_column('extracted_scents', 'notes')
    op.drop_column('scent_memories', 'summary')
    op.add_column('scent_profiles', sa.Column('note_occurrence_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('scent_profiles', 'top_notes')
    op.drop_column('scent_profiles', 'heart_notes')
    op.drop_column('scent_profiles', 'budget_range')
    op.drop_column('scent_profiles', 'intensity_preference')
    op.drop_column('scent_profiles', 'base_notes')
    op.add_column('spotify_links', sa.Column('lyrics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_links', 'lyrics')
    op.add_column('scent_profiles', sa.Column('base_notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('scent_profiles', sa.Column('intensity_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('scent_profiles', sa.Column('budget_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('scent_profiles', sa.Column('heart_notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('scent_profiles', sa.Column('top_notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('scent_profiles', 'note_occurrence_counts')
    op.add_column('scent_memories', sa.Column('summary', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('extracted_scents', sa.Column('notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('extracted_scents', 'emotion')
    op.drop_column('extracted_scents', 'color')
    op.drop_column('extracted_scents', 'base_notes')
    op.drop_column('extracted_scents', 'heart_notes')
    op.drop_column('extracted_scents', 'top_notes')
    op.drop_column('extracted_scents', 'scent_family')
    # ### end Alembic commands ###
